### ISSUE TITLE
Try to understand - Advanced: Sync all branches

### ISSUE THREAD

**Issue by nicolarohner1337** [wei/git-sync#14]
**To Sync all branches from source to destination, use** 

source_branch: "refs/remotes/source/*" 
and
destination_branch: "refs/heads/*"
But be careful, branches with the same name including master will be overwritten.

So In my case 

SOURCE REPO:
BRANCHES X,Y,Z

DESTINATION REPO:
BRANCHES X,Y,Z

In my case a HEAD branch gets added to the destination repo - correct?

```
# This is a basic workflow to help you get started with Actions

name: Sync Repo

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches:
    - dev
    - qa
    - prod
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  repo-sync:
    runs-on: ubuntu-latest
    steps:
    - name: repo-sync
      uses: wei/git-sync@v2
      with:
        source_repo: "https://${{ secrets.USER_NAME }}:${{ secrets.REPO_SYNC_TOKEN }}@github.com/interdiscount/tealium.git"
        source_branch: "refs/remotes/source/*"
        destination_repo: "https://${{ secrets.USER_NAME }}:${{ secrets.REPO_SYNC_TOKEN }}@github.com/coopanalytics/tealium-lib-msp-id.git"
        destination_branch: "refs/heads/*"
```
