### ISSUE TITLE
Sync all branches AND all tags?

### ISSUE THREAD

**Issue by connecteev** [wei/git-sync#19]
I'm trying to sync both **all branches** as well as **all tags**, but the yml doesnt accept two ```with``` clauses. Any ideas?

```
# File: .github/workflows/git-sync.yml

name: Git Sync # from https://github.com/wei/git-sync
on:
  push:
  schedule:
  - cron: "*/3 * * * *"  # runs every 3 mins (for now)

jobs:
  git-sync:
    runs-on: ubuntu-latest
    steps:
    - name: git-sync
      uses: wei/git-sync@v2
      with:
        source_repo: "https://connecteev:${{ secrets.MY_PERSONAL_ACCESS_TOKEN_FROM_GITHUB_SETTINGS }}@github.com/xxxxxxxxxx/yyyyyyyyyyy.git"
        source_branch: "refs/remotes/source/*"
        destination_repo: "https://connecteev:${{ secrets.MY_PERSONAL_ACCESS_TOKEN_FROM_GITHUB_SETTINGS }}@github.com/connecteev/yyyyyyyyyyy.git"
        destination_branch: "refs/heads/*"

      with:
        source_repo: "https://connecteev:${{ secrets.MY_PERSONAL_ACCESS_TOKEN_FROM_GITHUB_SETTINGS }}@github.com/xxxxxxxxxx/yyyyyyyyyyy.git"
        source_branch: "refs/tags/*"
        destination_repo: "https://connecteev:${{ secrets.MY_PERSONAL_ACCESS_TOKEN_FROM_GITHUB_SETTINGS }}@github.com/connecteev/yyyyyyyyyyy.git"
        destination_branch: "refs/tags/*"
```
