### ISSUE TITLE
destination_repo doesn't accept `org/repository` as the value

### ISSUE THREAD

**Issue by trivikr** [wei/git-sync#26]
**Describe the bug**
The configuration `source_repo` accepts `org/repository` as the value, but `destination_repo` does not.

**To Reproduce**
Create a config which passes `org/repository` as the value for destination address.

<details>
<summary>Example config</summary>

```
name: git-sync

on:
  # Triggers the workflow on push events but only for the main branch
  push:
    branches: [ main ]

jobs:
  git-sync:
    runs-on: ubuntu-latest

    steps:
      - name: git-sync
        uses: wei/git-sync@v3
        with:
          source_repo: "source_org/repository"
          source_branch: "main"
          destination_repo: "destination_org/repository" 
          destination_branch: "main"
          source_ssh_private_key: ${{ secrets.SOURCE_SSH_PRIVATE_KEY }}
          destination_ssh_private_key:  ${{ secrets.DESTINATION_SSH_PRIVATE_KEY }}
```

</details>

Tested with:
* source_repo: `"trivikr/git-sync-test"`
* destination_repo: `"trivikr/private-git-sync-test"`
* example GitHub Action run: https://github.com/trivikr/git-sync-test/runs/1778016093?check_suite_focus=true

<details>
<summary>Example GitHub Action run output</summary>

```console
Cloning into '/root/source'...
SOURCE=git@github.com:trivikr/git-sync-test.git:main
DESTINATION=trivikr/private-git-sync-test.git:main
Warning: Permanently added 'github.com,140.82.113.4' (RSA) to the list of known hosts.
Warning: Permanently added the RSA host key for IP address '140.82.112.4' to the list of known hosts.
* main                a60328d [source/main] fix: remove check for secrets.GIT_SYNC_DESTINATION_REPO
  remotes/source/HEAD -> source/main
  remotes/source/main a60328d fix: remove check for secrets.GIT_SYNC_DESTINATION_REPO
fatal: could not read Username for 'github.com': No such device or address
```

</details>

Output: The GitHub Action run fails with `fatal: could not read Username for 'github.com': No such device or address`

Issue: `DESTINATION` is `trivikr/private-git-sync-test.git:main` instead of `git@github.com:trivikr/git-sync-test.git:main`

**Expected behavior**
The git sync is successful between `"source_org/repository"` and `"destination_org/repository"` when `""destination_org/repository"` is passed in configuration `destination_repo`

**Screenshots**

<details>
<summary>Screenshot</summary>

![Screen Shot 2021-01-27 at 8 05 26 AM](https://user-images.githubusercontent.com/16024985/106018567-8349ee80-6076-11eb-8b40-57ddd15796a7.png)

</details>

**Additional context**
This issue was identified while testing suggestion in fix https://github.com/wei/git-sync/issues/25#issuecomment-768107107
