### ISSUE TITLE
Help neede to set up my action

### ISSUE THREAD

**Issue by ghost** [wei/git-sync#35]
Sorry for my abyssal incompetence with 'Actions', this is my code:
```
name: Sync to public website shriveling.github.io

# Controls when the action will run. 
on:
  push:
    branches: [ gh-pages ]
  pull_request:
    branches: [ gh-pages ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
jobs:
  git-sync:
    runs-on: ubuntu-latest
    steps:
      - name: git-sync
        uses: wei/git-sync@v3
        with:
          source_repo: " theworldisnotflat/shriveling_world "
          source_branch: "gh-pages"
          destination_repo: "shriveling/shriveling.github.io"
          destination_branch: "gh-pages"
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY_RSA }} # optional
```
 and the resulting error after run.
I want to sync a branch between two repositories
Is ssh_key necessary?
```
Run wei/git-sync@v3
  with:
    source_repo:  theworldisnotflat/shriveling_world 
    source_branch: gh-pages
    destination_repo: shriveling/shriveling.github.io
    destination_branch: gh-pages
    ssh_private_key: ***
  
/usr/bin/docker run --name e4872fbb9d37d34a2f8f47885462a6ea4d_31f8ae --label 5588e4 --workdir /github/workspace --rm -e INPUT_SOURCE_REPO -e INPUT_SOURCE_BRANCH -e INPUT_DESTINATION_REPO -e INPUT_DESTINATION_BRANCH -e INPUT_SSH_PRIVATE_KEY -e INPUT_SOURCE_SSH_PRIVATE_KEY -e INPUT_DESTINATION_SSH_PRIVATE_KEY -e SSH_PRIVATE_KEY -e SOURCE_SSH_PRIVATE_KEY -e DESTINATION_SSH_PRIVATE_KEY -e HOME -e GITHUB_JOB -e GITHUB_REF -e GITHUB_SHA -e GITHUB_REPOSITORY -e GITHUB_REPOSITORY_OWNER -e GITHUB_RUN_ID -e GITHUB_RUN_NUMBER -e GITHUB_RETENTION_DAYS -e GITHUB_ACTOR -e GITHUB_WORKFLOW -e GITHUB_HEAD_REF -e GITHUB_BASE_REF -e GITHUB_EVENT_NAME -e GITHUB_SERVER_URL -e GITHUB_API_URL -e GITHUB_GRAPHQL_URL -e GITHUB_WORKSPACE -e GITHUB_ACTION -e GITHUB_EVENT_PATH -e GITHUB_ACTION_REPOSITORY -e GITHUB_ACTION_REF -e GITHUB_PATH -e GITHUB_ENV -e RUNNER_OS -e RUNNER_TOOL_CACHE -e RUNNER_TEMP -e RUNNER_WORKSPACE -e ACTIONS_RUNTIME_URL -e ACTIONS_RUNTIME_TOKEN -e ACTIONS_CACHE_URL -e GITHUB_ACTIONS=true -e CI=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/_temp/_runner_file_commands":"/github/file_commands" -v "/home/runner/work/shriveling_world/shriveling_world":"/github/workspace" 5588e4:872fbb9d37d34a2f8f47885462a6ea4d  " theworldisnotflat/shriveling_world " "gh-pages" "shriveling/shriveling.github.io" "gh-pages"
SOURCE=git@github.com:theworldisnotflat/shriveling_world.git:gh-pages
Cloning into '/root/source'...
DESTINATION=git@github.com:shriveling/shriveling.github.io.git:gh-pages
Warning: Permanently added 'github.com,140.82.114.4' (RSA) to the list of known hosts.
Load key "/root/.ssh/id_rsa": invalid format
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
fatal: not a git repository (or any parent up to mount point /github)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
```
